export const CHARACTER_CLASESS = [
  {
    name: 'elementals',
    humanName: 'Elementals',
    variants: [
      'crystal_mauler',
      'fire_knight',
      'ground_monk',
      'leaf_ranger',
      'metal_bladekeeper',
      'water_priestess',
      'wind_hashashin',
    ],
  },
  {
    name: 'medieval',
    humanName: 'Medieval',
    variants: [
      'adventurer_01',
      'adventurer_02',
      'adventurer_03',
      'adventurer_04',
      'adventurer_05',
      'barkeep',
      'barmaid',
      'beggar',
      'blacksmith',
      'captain',
      'dog',
      'dwarf',
      'elder',
      'fairy',
      'farmer_01',
      'guard',
      'gypsy',
      'jester',
      'king',
      'merchant',
      'mermaid',
      'minstrel',
      'priestess',
      'princess',
      'shady_guy',
      'stranger',
      'villager_01',
      'villager_02',
      'witch',
    ],
  },
  {
    name: 'steampunk',
    humanName: 'Steampunk',
    variants: [
      'aristocrat_01',
      'aristocrat_02',
      'bartender',
      'engineer_01',
      'engineer_02',
      'gunslinger',
      'masked_man',
      'masked_woman',
      'steambot_01',
      'steambot_02',
      'steambot_03',
      'trader',
    ],
  },
];
